/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 blender-test-world.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/blender-test-world-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <pointLight name="Point" intensity={1190.3} decay={2} color="#daff05" position={[0.1, 2.97, 0.94]} rotation={[-Math.PI / 2, 0, 0]} />
        <pointLight name="boxlight2" intensity={543.51} decay={2} color="#bc3aff" position={[1.24, 0.55, -0.61]} rotation={[-Math.PI / 2, 0, 0]} />
        <pointLight name="boxlight1" intensity={543.51} decay={2} color="#bc3aff" position={[0.32, 0.55, -0.61]} rotation={[-Math.PI / 2, 0, 0]} />
        <group name="scaleBox" position={[-1.23, 1.01, 1.15]}>
          <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.red} />
          <mesh name="Cube_1" geometry={nodes.Cube_1.geometry} material={materials.gray} />
        </group>
        <mesh name="backdrop" geometry={nodes.backdrop.geometry} material={materials.blush} position={[0.31, 3.31, 1.32]} scale={3.3} />
        <mesh name="floorGrid" geometry={nodes.floorGrid.geometry} material={materials.gridGray} position={[1.11, 0.01, 1.11]} />
        <mesh name="boxBase" geometry={nodes.boxBase.geometry} material={materials.gold} position={[0.31, 0.34, -0.8]} scale={0.33} />
        <mesh name="boxLid" geometry={nodes.boxLid.geometry} material={materials.gold} position={[0.74, 0.72, -1.13]} rotation={[-Math.PI / 2, 0, 0]} scale={0.33} />
        <group name="boxPrize" position={[0.74, 0.35, -0.8]} rotation={[0, 0, -Math.PI / 2]} scale={[0.17, 0.54, 0.17]}>
          <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials.pink} />
          <mesh name="Cylinder_1" geometry={nodes.Cylinder_1.geometry} material={materials.lightPink} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/blender-test-world-transformed.glb')
