/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 ice-world.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ice-world-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <pointLight intensity={1.57} decay={2} color="#437cff" position={[-28.17, 7.11, 13.72]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={1.57} decay={2} color="#437cff" position={[-8.69, 7.11, 15.35]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={1.57} decay={2} color="#437cff" position={[1.5, 7.11, 29.13]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={1.57} decay={2} color="#437cff" position={[23.46, 7.11, 31.71]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={1.57} decay={2} color="#437cff" position={[18.33, 7.11, -26.03]} rotation={[-Math.PI / 2, 0, 0]} />
      <spotLight intensity={41.63} angle={Math.PI / 8} penumbra={0.15} decay={2} color="#437cff" position={[-8.69, 11.33, 15.35]} rotation={[-Math.PI / 2, 0, 0]} />
      <spotLight intensity={41.63} angle={Math.PI / 8} penumbra={0.15} decay={2} color="#437cff" position={[1.57, 11.33, 29.26]} rotation={[-Math.PI / 2, 0, 0]} />
      <spotLight intensity={41.63} angle={Math.PI / 8} penumbra={0.15} decay={2} color="#437cff" position={[23.33, 11.33, 31.74]} rotation={[-Math.PI / 2, 0, 0]} />
      <spotLight intensity={41.63} angle={Math.PI / 8} penumbra={0.15} decay={2} color="#437cff" position={[18.32, 11.33, -25.81]} rotation={[-Math.PI / 2, 0, 0]} />
      <spotLight intensity={41.63} angle={Math.PI / 8} penumbra={0.15} decay={2} color="#437cff" position={[-28.22, 11.33, 13.76]} rotation={[-Math.PI / 2, 0, 0]} />
      <directionalLight intensity={0.01} decay={2} color="#c8b0ff" rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.floor.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.iceburgs.geometry} material={materials.Ice} position={[30.49, 2.37, 43.36]} scale={-5.88} />
      <mesh geometry={nodes.lamppost.geometry} material={nodes.lamppost.material} position={[-28.21, 0, 13.77]} scale={0.23} />
      <mesh geometry={nodes.lamppost001.geometry} material={nodes.lamppost001.material} position={[-8.73, 0, 15.4]} scale={0.23} />
      <mesh geometry={nodes.lamppost002.geometry} material={nodes.lamppost002.material} position={[1.46, 0, 29.18]} scale={0.23} />
      <mesh geometry={nodes.lamppost003.geometry} material={nodes.lamppost003.material} position={[23.42, 0, 31.76]} scale={0.23} />
      <mesh geometry={nodes.lamppost004.geometry} material={nodes.lamppost004.material} position={[18.29, 0, -25.98]} scale={0.23} />
    </group>
  )
}

useGLTF.preload('/ice-world-transformed.glb')
